server:
  port: 5041

spring:
  application:
    name: peggi
  config:
    import:
      - classpath:/yml/application-local.yml
      - classpath:/yml/application-prod.yml

openrouter:
  api:
    key: your_openrouter_api_key

